server:
  servlet:
    context-path: /ludy
spring:
  application:
    name: ludy
  data:
    mongodb:
      uri: ${DATA_BASE_URI}
springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
  api-docs:
    path: /api/api-docs